package webhook

// StoryCreateEvent represents the story create event.
type StoryCreateEvent struct {
	Event             EventType `json:"event,omitempty"`
	EventFrom         string    `json:"event_from,omitempty"`
	Referer           string    `json:"referer,omitempty"`
	WorkspaceID       string    `json:"workspace_id,omitempty"`
	CurrentUser       string    `json:"current_user,omitempty"`
	ID                string    `json:"id,omitempty"`
	Name              string    `json:"name,omitempty"`
	Description       string    `json:"description,omitempty"`
	DescriptionType   string    `json:"description_type,omitempty"`
	Owner             string    `json:"owner,omitempty"`
	Begin             string    `json:"begin,omitempty"`
	Due               string    `json:"due,omitempty"`
	Creator           string    `json:"creator,omitempty"`
	Priority          string    `json:"priority,omitempty"`
	WorkitemTypeID    string    `json:"workitem_type_id,omitempty"`
	Status            string    `json:"status,omitempty"`
	TemplatedID       string    `json:"templated_id,omitempty"`
	EntityType        string    `json:"entity_type,omitempty"`
	Remain            string    `json:"remain,omitempty"`
	ParentID          string    `json:"parent_id,omitempty"`
	AncestorID        string    `json:"ancestor_id,omitempty"`
	ChildrenID        string    `json:"children_id,omitempty"`
	Secret            string    `json:"secret,omitempty"`
	RioToken          string    `json:"rio_token,omitempty"`
	CustomFieldOne    string    `json:"custom_field_one,omitempty"`
	CustomFieldTwo    string    `json:"custom_field_two,omitempty"`
	CustomFieldThree  string    `json:"custom_field_three,omitempty"`
	CustomFieldFour   string    `json:"custom_field_four,omitempty"`
	CustomFieldFive   string    `json:"custom_field_five,omitempty"`
	CustomFieldSix    string    `json:"custom_field_six,omitempty"`
	CustomFieldSeven  string    `json:"custom_field_seven,omitempty"`
	CustomFieldEight  string    `json:"custom_field_eight,omitempty"`
	CustomField9      string    `json:"custom_field_9,omitempty"`
	CustomField10     string    `json:"custom_field_10,omitempty"`
	CustomField11     string    `json:"custom_field_11,omitempty"`
	CustomField12     string    `json:"custom_field_12,omitempty"`
	CustomField13     string    `json:"custom_field_13,omitempty"`
	CustomField14     string    `json:"custom_field_14,omitempty"`
	CustomField15     string    `json:"custom_field_15,omitempty"`
	CustomField16     string    `json:"custom_field_16,omitempty"`
	CustomField17     string    `json:"custom_field_17,omitempty"`
	CustomField18     string    `json:"custom_field_18,omitempty"`
	CustomField19     string    `json:"custom_field_19,omitempty"`
	CustomField20     string    `json:"custom_field_20,omitempty"`
	CustomField21     string    `json:"custom_field_21,omitempty"`
	CustomField22     string    `json:"custom_field_22,omitempty"`
	CustomField23     string    `json:"custom_field_23,omitempty"`
	CustomField24     string    `json:"custom_field_24,omitempty"`
	CustomField25     string    `json:"custom_field_25,omitempty"`
	CustomField26     string    `json:"custom_field_26,omitempty"`
	CustomField27     string    `json:"custom_field_27,omitempty"`
	CustomField28     string    `json:"custom_field_28,omitempty"`
	CustomField29     string    `json:"custom_field_29,omitempty"`
	CustomField30     string    `json:"custom_field_30,omitempty"`
	CustomField31     string    `json:"custom_field_31,omitempty"`
	CustomField32     string    `json:"custom_field_32,omitempty"`
	CustomField33     string    `json:"custom_field_33,omitempty"`
	CustomField34     string    `json:"custom_field_34,omitempty"`
	CustomField35     string    `json:"custom_field_35,omitempty"`
	CustomField36     string    `json:"custom_field_36,omitempty"`
	CustomField37     string    `json:"custom_field_37,omitempty"`
	CustomField38     string    `json:"custom_field_38,omitempty"`
	CustomField39     string    `json:"custom_field_39,omitempty"`
	CustomField40     string    `json:"custom_field_40,omitempty"`
	CustomField41     string    `json:"custom_field_41,omitempty"`
	CustomField42     string    `json:"custom_field_42,omitempty"`
	CustomField43     string    `json:"custom_field_43,omitempty"`
	CustomField44     string    `json:"custom_field_44,omitempty"`
	CustomField45     string    `json:"custom_field_45,omitempty"`
	CustomField46     string    `json:"custom_field_46,omitempty"`
	CustomField47     string    `json:"custom_field_47,omitempty"`
	CustomField48     string    `json:"custom_field_48,omitempty"`
	CustomField49     string    `json:"custom_field_49,omitempty"`
	CustomField50     string    `json:"custom_field_50,omitempty"`
	CustomPlanField1  string    `json:"custom_plan_field_1,omitempty"`
	CustomPlanField2  string    `json:"custom_plan_field_2,omitempty"`
	CustomPlanField3  string    `json:"custom_plan_field_3,omitempty"`
	CustomPlanField4  string    `json:"custom_plan_field_4,omitempty"`
	CustomPlanField5  string    `json:"custom_plan_field_5,omitempty"`
	CustomPlanField6  string    `json:"custom_plan_field_6,omitempty"`
	CustomPlanField7  string    `json:"custom_plan_field_7,omitempty"`
	CustomPlanField8  string    `json:"custom_plan_field_8,omitempty"`
	CustomPlanField9  string    `json:"custom_plan_field_9,omitempty"`
	CustomPlanField10 string    `json:"custom_plan_field_10,omitempty"`
	DevProxyHost      string    `json:"devproxy_host,omitempty"`
	QueueID           string    `json:"queue_id,omitempty"`
	EventID           string    `json:"event_id,omitempty"`
	Created           string    `json:"created,omitempty"`
}

// StoryUpdateEvent represents the story update event.
type StoryUpdateEvent struct {
	Event                  EventType `json:"event,omitempty"`
	EventFrom              string    `json:"event_from,omitempty"`
	Referer                string    `json:"referer,omitempty"`
	WorkspaceID            string    `json:"workspace_id,omitempty"`
	CurrentUser            string    `json:"current_user,omitempty"`
	ID                     string    `json:"id,omitempty"`
	ChangeFields           string    `json:"change_fields,omitempty"`
	Secret                 string    `json:"secret,omitempty"`
	RioToken               string    `json:"rio_token,omitempty"`
	DevProxyHost           string    `json:"devproxy_host,omitempty"`
	QueueID                string    `json:"queue_id,omitempty"`
	EventID                string    `json:"event_id,omitempty"`
	Created                string    `json:"created,omitempty"`
	OldID                  string    `json:"old_id"`
	OldSecretRootID        string    `json:"old_secret_root_id"`
	OldSort                string    `json:"old_sort"`
	OldWorkitemTypeID      string    `json:"old_workitem_type_id"`
	OldName                string    `json:"old_name"`
	OldDescription         string    `json:"old_description"`
	OldMarkdownDescription string    `json:"old_markdown_description"`
	OldDescriptionType     string    `json:"old_description_type"`
	OldCreator             string    `json:"old_creator"`
	OldCreated             string    `json:"old_created"`
	OldModified            string    `json:"old_modified"`
	OldParentID            string    `json:"old_parent_id"`
	OldChildrenID          string    `json:"old_children_id"`
	OldAncestorID          string    `json:"old_ancestor_id"`
	OldPath                string    `json:"old_path"`
	OldLevel               string    `json:"old_level"`
	OldWorkspaceID         string    `json:"old_workspace_id"`
	OldStatus              string    `json:"old_status"`
	OldAppID               string    `json:"old_app_id"`
	OldFlows               string    `json:"old_flows"`
	OldPriority            string    `json:"old_priority"`
	OldOwner               string    `json:"old_owner"`
	OldParticipator        string    `json:"old_participator"`
	OldCC                  string    `json:"old_cc"`
	OldBegin               string    `json:"old_begin"`
	OldDue                 string    `json:"old_due"`
	OldSource              string    `json:"old_source"`
	OldWorkitemID          string    `json:"old_workitem_id"`
	OldIterationID         string    `json:"old_iteration_id"`
	OldIssueID             string    `json:"old_issue_id"`
	OldSupportID           string    `json:"old_support_id"`
	OldSupportForumID      string    `json:"old_support_forum_id"`
	OldModule              string    `json:"old_module"`
	OldCompleted           string    `json:"old_completed"`
	OldTemplatedID         string    `json:"old_templated_id"`
	OldDelayCount          string    `json:"old_delay_count"`
	OldType                string    `json:"old_type"`
	OldStatusAppend        string    `json:"old_status_append"`
	OldBusinessValue       string    `json:"old_business_value"`
	OldTechRisk            string    `json:"old_tech_risk"`
	OldSize                string    `json:"old_size"`
	OldImportFlag          string    `json:"old_import_flag"`
	OldEffort              string    `json:"old_effort"`
	OldEffortCompleted     string    `json:"old_effort_completed"`
	OldExceed              string    `json:"old_exceed"`
	OldRemain              string    `json:"old_remain"`
	OldProgress            string    `json:"old_progress"`
	OldReleaseID           string    `json:"old_release_id"`
	OldFeature             string    `json:"old_feature"`
	OldEntityType          string    `json:"old_entity_type"`
	OldCustomFieldOne      string    `json:"old_custom_field_one"`
	OldCustomFieldTwo      string    `json:"old_custom_field_two"`
	OldCustomFieldThree    string    `json:"old_custom_field_three"`
	OldCustomFieldFour     string    `json:"old_custom_field_four"`
	OldCustomFieldFive     string    `json:"old_custom_field_five"`
	OldCustomFieldSix      string    `json:"old_custom_field_six"`
	OldCustomFieldSeven    string    `json:"old_custom_field_seven"`
	OldCustomFieldEight    string    `json:"old_custom_field_eight"`
	OldAttachmentCount     string    `json:"old_attachment_count"`
	OldHasAttachment       string    `json:"old_has_attachment"`
	OldDeveloper           string    `json:"old_developer"`
	OldBugID               string    `json:"old_bug_id"`
	OldTestFocus           string    `json:"old_test_focus"`
	OldCategoryID          string    `json:"old_category_id"`
	OldVersion             string    `json:"old_version"`
	OldConfidential        string    `json:"old_confidential"`
	OldCreatedFrom         string    `json:"old_created_from"`
	OldFollower            string    `json:"old_follower"`
	OldSyncType            string    `json:"old_sync_type"`
	OldPredecessorCount    string    `json:"old_predecessor_count"`
	OldIsArchived          string    `json:"old_is_archived"`
	OldModifier            string    `json:"old_modifier"`
	OldProgressManual      string    `json:"old_progress_manual"`
	OldSuccessorCount      string    `json:"old_successor_count"`
	OldLabel               string    `json:"old_label"`
	OldStep                string    `json:"old_step"`
	OldCustomField9        string    `json:"old_custom_field_9"`
	OldCustomField10       string    `json:"old_custom_field_10"`
	OldCustomField11       string    `json:"old_custom_field_11"`
	OldCustomField12       string    `json:"old_custom_field_12"`
	OldCustomField13       string    `json:"old_custom_field_13"`
	OldCustomField14       string    `json:"old_custom_field_14"`
	OldCustomField15       string    `json:"old_custom_field_15"`
	OldCustomField16       string    `json:"old_custom_field_16"`
	OldCustomField17       string    `json:"old_custom_field_17"`
	OldCustomField18       string    `json:"old_custom_field_18"`
	OldCustomField19       string    `json:"old_custom_field_19"`
	OldCustomField20       string    `json:"old_custom_field_20"`
	OldCustomField21       string    `json:"old_custom_field_21"`
	OldCustomField22       string    `json:"old_custom_field_22"`
	OldCustomField23       string    `json:"old_custom_field_23"`
	OldCustomField24       string    `json:"old_custom_field_24"`
	OldCustomField25       string    `json:"old_custom_field_25"`
	OldCustomField26       string    `json:"old_custom_field_26"`
	OldCustomField27       string    `json:"old_custom_field_27"`
	OldCustomField28       string    `json:"old_custom_field_28"`
	OldCustomField29       string    `json:"old_custom_field_29"`
	OldCustomField30       string    `json:"old_custom_field_30"`
	OldCustomField31       string    `json:"old_custom_field_31"`
	OldCustomField32       string    `json:"old_custom_field_32"`
	OldCustomField33       string    `json:"old_custom_field_33"`
	OldCustomField34       string    `json:"old_custom_field_34"`
	OldCustomField35       string    `json:"old_custom_field_35"`
	OldCustomField36       string    `json:"old_custom_field_36"`
	OldCustomField37       string    `json:"old_custom_field_37"`
	OldCustomField38       string    `json:"old_custom_field_38"`
	OldCustomField39       string    `json:"old_custom_field_39"`
	OldCustomField40       string    `json:"old_custom_field_40"`
	OldCustomField41       string    `json:"old_custom_field_41"`
	OldCustomField42       string    `json:"old_custom_field_42"`
	OldCustomField43       string    `json:"old_custom_field_43"`
	OldCustomField44       string    `json:"old_custom_field_44"`
	OldCustomField45       string    `json:"old_custom_field_45"`
	OldCustomField46       string    `json:"old_custom_field_46"`
	OldCustomField47       string    `json:"old_custom_field_47"`
	OldCustomField48       string    `json:"old_custom_field_48"`
	OldCustomField49       string    `json:"old_custom_field_49"`
	OldCustomField50       string    `json:"old_custom_field_50"`
	OldCustomField51       string    `json:"old_custom_field_51"`
	OldCustomField52       string    `json:"old_custom_field_52"`
	OldCustomField53       string    `json:"old_custom_field_53"`
	OldCustomField54       string    `json:"old_custom_field_54"`
	OldCustomField55       string    `json:"old_custom_field_55"`
	OldCustomField56       string    `json:"old_custom_field_56"`
	OldCustomField57       string    `json:"old_custom_field_57"`
	OldCustomField58       string    `json:"old_custom_field_58"`
	OldCustomField59       string    `json:"old_custom_field_59"`
	OldCustomField60       string    `json:"old_custom_field_60"`
	OldCustomField61       string    `json:"old_custom_field_61"`
	OldCustomField62       string    `json:"old_custom_field_62"`
	OldCustomField63       string    `json:"old_custom_field_63"`
	OldCustomField64       string    `json:"old_custom_field_64"`
	OldCustomField65       string    `json:"old_custom_field_65"`
	OldCustomField66       string    `json:"old_custom_field_66"`
	OldCustomField67       string    `json:"old_custom_field_67"`
	OldCustomField68       string    `json:"old_custom_field_68"`
	OldCustomField69       string    `json:"old_custom_field_69"`
	OldCustomField70       string    `json:"old_custom_field_70"`
	OldCustomField71       string    `json:"old_custom_field_71"`
	OldCustomField72       string    `json:"old_custom_field_72"`
	OldCustomField73       string    `json:"old_custom_field_73"`
	OldCustomField74       string    `json:"old_custom_field_74"`
	OldCustomField75       string    `json:"old_custom_field_75"`
	OldCustomField76       string    `json:"old_custom_field_76"`
	OldCustomField77       string    `json:"old_custom_field_77"`
	OldCustomField78       string    `json:"old_custom_field_78"`
	OldCustomField79       string    `json:"old_custom_field_79"`
	OldCustomField80       string    `json:"old_custom_field_80"`
	OldCustomField81       string    `json:"old_custom_field_81"`
	OldCustomField82       string    `json:"old_custom_field_82"`
	OldCustomField83       string    `json:"old_custom_field_83"`
	OldCustomField84       string    `json:"old_custom_field_84"`
	OldCustomField85       string    `json:"old_custom_field_85"`
	OldCustomField86       string    `json:"old_custom_field_86"`
	OldCustomField87       string    `json:"old_custom_field_87"`
	OldCustomField88       string    `json:"old_custom_field_88"`
	OldCustomField89       string    `json:"old_custom_field_89"`
	OldCustomField90       string    `json:"old_custom_field_90"`
	OldCustomField91       string    `json:"old_custom_field_91"`
	OldCustomField92       string    `json:"old_custom_field_92"`
	OldCustomField93       string    `json:"old_custom_field_93"`
	OldCustomField94       string    `json:"old_custom_field_94"`
	OldCustomField95       string    `json:"old_custom_field_95"`
	OldCustomField96       string    `json:"old_custom_field_96"`
	OldCustomField97       string    `json:"old_custom_field_97"`
	OldCustomField98       string    `json:"old_custom_field_98"`
	OldCustomField99       string    `json:"old_custom_field_99"`
	OldCustomField100      string    `json:"old_custom_field_100"`
	OldCustomField101      string    `json:"old_custom_field_101"`
	OldCustomField102      string    `json:"old_custom_field_102"`
	OldCustomField103      string    `json:"old_custom_field_103"`
	OldCustomField104      string    `json:"old_custom_field_104"`
	OldCustomField105      string    `json:"old_custom_field_105"`
	OldCustomField106      string    `json:"old_custom_field_106"`
	OldCustomField107      string    `json:"old_custom_field_107"`
	OldCustomField108      string    `json:"old_custom_field_108"`
	OldCustomField109      string    `json:"old_custom_field_109"`
	OldCustomField110      string    `json:"old_custom_field_110"`
	OldCustomField111      string    `json:"old_custom_field_111"`
	OldCustomField112      string    `json:"old_custom_field_112"`
	OldCustomField113      string    `json:"old_custom_field_113"`
	OldCustomField114      string    `json:"old_custom_field_114"`
	OldCustomField115      string    `json:"old_custom_field_115"`
	OldCustomField116      string    `json:"old_custom_field_116"`
	OldCustomField117      string    `json:"old_custom_field_117"`
	OldCustomField118      string    `json:"old_custom_field_118"`
	OldCustomField119      string    `json:"old_custom_field_119"`
	OldCustomField120      string    `json:"old_custom_field_120"`
	OldCustomField121      string    `json:"old_custom_field_121"`
	OldCustomField122      string    `json:"old_custom_field_122"`
	OldCustomField123      string    `json:"old_custom_field_123"`
	OldCustomField124      string    `json:"old_custom_field_124"`
	OldCustomField125      string    `json:"old_custom_field_125"`
	OldCustomField126      string    `json:"old_custom_field_126"`
	OldCustomField127      string    `json:"old_custom_field_127"`
	OldCustomField128      string    `json:"old_custom_field_128"`
	OldCustomField129      string    `json:"old_custom_field_129"`
	OldCustomField130      string    `json:"old_custom_field_130"`
	OldCustomField131      string    `json:"old_custom_field_131"`
	OldCustomField132      string    `json:"old_custom_field_132"`
	OldCustomField133      string    `json:"old_custom_field_133"`
	OldCustomField134      string    `json:"old_custom_field_134"`
	OldCustomField135      string    `json:"old_custom_field_135"`
	OldCustomField136      string    `json:"old_custom_field_136"`
	OldCustomField137      string    `json:"old_custom_field_137"`
	OldCustomField138      string    `json:"old_custom_field_138"`
	OldCustomField139      string    `json:"old_custom_field_139"`
	OldCustomField140      string    `json:"old_custom_field_140"`
	OldCustomField141      string    `json:"old_custom_field_141"`
	OldCustomField142      string    `json:"old_custom_field_142"`
	OldCustomField143      string    `json:"old_custom_field_143"`
	OldCustomField144      string    `json:"old_custom_field_144"`
	OldCustomField145      string    `json:"old_custom_field_145"`
	OldCustomField146      string    `json:"old_custom_field_146"`
	OldCustomField147      string    `json:"old_custom_field_147"`
	OldCustomField148      string    `json:"old_custom_field_148"`
	OldCustomField149      string    `json:"old_custom_field_149"`
	OldCustomField150      string    `json:"old_custom_field_150"`
	OldCustomField151      string    `json:"old_custom_field_151"`
	OldCustomField152      string    `json:"old_custom_field_152"`
	OldCustomField153      string    `json:"old_custom_field_153"`
	OldCustomField154      string    `json:"old_custom_field_154"`
	OldCustomField155      string    `json:"old_custom_field_155"`
	OldCustomField156      string    `json:"old_custom_field_156"`
	OldCustomField157      string    `json:"old_custom_field_157"`
	OldCustomField158      string    `json:"old_custom_field_158"`
	OldCustomField159      string    `json:"old_custom_field_159"`
	OldCustomField160      string    `json:"old_custom_field_160"`
	OldCustomField161      string    `json:"old_custom_field_161"`
	OldCustomField162      string    `json:"old_custom_field_162"`
	OldCustomField163      string    `json:"old_custom_field_163"`
	OldCustomField164      string    `json:"old_custom_field_164"`
	OldCustomField165      string    `json:"old_custom_field_165"`
	OldCustomField166      string    `json:"old_custom_field_166"`
	OldCustomField167      string    `json:"old_custom_field_167"`
	OldCustomField168      string    `json:"old_custom_field_168"`
	OldCustomField169      string    `json:"old_custom_field_169"`
	OldCustomField170      string    `json:"old_custom_field_170"`
	OldCustomField171      string    `json:"old_custom_field_171"`
	OldCustomField172      string    `json:"old_custom_field_172"`
	OldCustomField173      string    `json:"old_custom_field_173"`
	OldCustomField174      string    `json:"old_custom_field_174"`
	OldCustomField175      string    `json:"old_custom_field_175"`
	OldCustomField176      string    `json:"old_custom_field_176"`
	OldCustomField177      string    `json:"old_custom_field_177"`
	OldCustomField178      string    `json:"old_custom_field_178"`
	OldCustomField179      string    `json:"old_custom_field_179"`
	OldCustomField180      string    `json:"old_custom_field_180"`
	OldCustomField181      string    `json:"old_custom_field_181"`
	OldCustomField182      string    `json:"old_custom_field_182"`
	OldCustomField183      string    `json:"old_custom_field_183"`
	OldCustomField184      string    `json:"old_custom_field_184"`
	OldCustomField185      string    `json:"old_custom_field_185"`
	OldCustomField186      string    `json:"old_custom_field_186"`
	OldCustomField187      string    `json:"old_custom_field_187"`
	OldCustomField188      string    `json:"old_custom_field_188"`
	OldCustomField189      string    `json:"old_custom_field_189"`
	OldCustomField190      string    `json:"old_custom_field_190"`
	OldCustomField191      string    `json:"old_custom_field_191"`
	OldCustomField192      string    `json:"old_custom_field_192"`
	OldCustomField193      string    `json:"old_custom_field_193"`
	OldCustomField194      string    `json:"old_custom_field_194"`
	OldCustomField195      string    `json:"old_custom_field_195"`
	OldCustomField196      string    `json:"old_custom_field_196"`
	OldCustomField197      string    `json:"old_custom_field_197"`
	OldCustomField198      string    `json:"old_custom_field_198"`
	OldCustomField199      string    `json:"old_custom_field_199"`
	OldCustomField200      string    `json:"old_custom_field_200"`
	OldCustomPlanField1    string    `json:"old_custom_plan_field_1"`
	OldCustomPlanField2    string    `json:"old_custom_plan_field_2"`
	OldCustomPlanField3    string    `json:"old_custom_plan_field_3"`
	OldCustomPlanField4    string    `json:"old_custom_plan_field_4"`
	OldCustomPlanField5    string    `json:"old_custom_plan_field_5"`
	OldCustomPlanField6    string    `json:"old_custom_plan_field_6"`
	OldCustomPlanField7    string    `json:"old_custom_plan_field_7"`
	OldCustomPlanField8    string    `json:"old_custom_plan_field_8"`
	OldCustomPlanField9    string    `json:"old_custom_plan_field_9"`
	OldCustomPlanField10   string    `json:"old_custom_plan_field_10"`

	NewID                  string `json:"new_id"`
	NewSecretRootID        string `json:"new_secret_root_id"`
	NewSort                string `json:"new_sort"`
	NewWorkitemTypeID      string `json:"new_workitem_type_id"`
	NewName                string `json:"new_name"`
	NewDescription         string `json:"new_description"`
	NewMarkdownDescription string `json:"new_markdown_description"`
	NewDescriptionType     string `json:"new_description_type"`
	NewCreator             string `json:"new_creator"`
	NewCreated             string `json:"new_created"`
	NewModified            string `json:"new_modified"`
	NewParentID            string `json:"new_parent_id"`
	NewChildrenID          string `json:"new_children_id"`
	NewAncestorID          string `json:"new_ancestor_id"`
	NewPath                string `json:"new_path"`
	NewLevel               string `json:"new_level"`
	NewWorkspaceID         string `json:"new_workspace_id"`
	NewStatus              string `json:"new_status"`
	NewAppID               string `json:"new_app_id"`
	NewFlows               string `json:"new_flows"`
	NewPriority            string `json:"new_priority"`
	NewOwner               string `json:"new_owner"`
	NewParticipator        string `json:"new_participator"`
	NewCC                  string `json:"new_cc"`
	NewBegin               string `json:"new_begin"`
	NewDue                 string `json:"new_due"`
	NewSource              string `json:"new_source"`
	NewWorkitemID          string `json:"new_workitem_id"`
	NewIterationID         string `json:"new_iteration_id"`
	NewIssueID             string `json:"new_issue_id"`
	NewSupportID           string `json:"new_support_id"`
	NewSupportForumID      string `json:"new_support_forum_id"`
	NewModule              string `json:"new_module"`
	NewCompleted           string `json:"new_completed"`
	NewTemplatedID         string `json:"new_templated_id"`
	NewDelayCount          string `json:"new_delay_count"`
	NewType                string `json:"new_type"`
	NewStatusAppend        string `json:"new_status_append"`
	NewBusinessValue       string `json:"new_business_value"`
	NewTechRisk            string `json:"new_tech_risk"`
	NewSize                string `json:"new_size"`
	NewImportFlag          string `json:"new_import_flag"`
	NewEffort              string `json:"new_effort"`
	NewEffortCompleted     string `json:"new_effort_completed"`
	NewExceed              string `json:"new_exceed"`
	NewRemain              string `json:"new_remain"`
	NewProgress            string `json:"new_progress"`
	NewReleaseID           string `json:"new_release_id"`
	NewFeature             string `json:"new_feature"`
	NewEntityType          string `json:"new_entity_type"`
	NewCustomFieldOne      string `json:"new_custom_field_one"`
	NewCustomFieldTwo      string `json:"new_custom_field_two"`
	NewCustomFieldThree    string `json:"new_custom_field_three"`
	NewCustomFieldFour     string `json:"new_custom_field_four"`
	NewCustomFieldFive     string `json:"new_custom_field_five"`
	NewCustomFieldSix      string `json:"new_custom_field_six"`
	NewCustomFieldSeven    string `json:"new_custom_field_seven"`
	NewCustomFieldEight    string `json:"new_custom_field_eight"`
	NewAttachmentCount     string `json:"new_attachment_count"`
	NewHasAttachment       string `json:"new_has_attachment"`
	NewDeveloper           string `json:"new_developer"`
	NewBugID               string `json:"new_bug_id"`
	NewTestFocus           string `json:"new_test_focus"`
	NewCategoryID          string `json:"new_category_id"`
	NewVersion             string `json:"new_version"`
	NewConfidential        string `json:"new_confidential"`
	NewCreatedFrom         string `json:"new_created_from"`
	NewFollower            string `json:"new_follower"`
	NewSyncType            string `json:"new_sync_type"`
	NewPredecessorCount    string `json:"new_predecessor_count"`
	NewIsArchived          string `json:"new_is_archived"`
	NewModifier            string `json:"new_modifier"`
	NewProgressManual      string `json:"new_progress_manual"`
	NewSuccessorCount      string `json:"new_successor_count"`
	NewLabel               string `json:"new_label"`
	NewStep                string `json:"new_step"`
	NewCustomField9        string `json:"new_custom_field_9"`
	NewCustomField10       string `json:"new_custom_field_10"`
	NewCustomField11       string `json:"new_custom_field_11"`
	NewCustomField12       string `json:"new_custom_field_12"`
	NewCustomField13       string `json:"new_custom_field_13"`
	NewCustomField14       string `json:"new_custom_field_14"`
	NewCustomField15       string `json:"new_custom_field_15"`
	NewCustomField16       string `json:"new_custom_field_16"`
	NewCustomField17       string `json:"new_custom_field_17"`
	NewCustomField18       string `json:"new_custom_field_18"`
	NewCustomField19       string `json:"new_custom_field_19"`
	NewCustomField20       string `json:"new_custom_field_20"`
	NewCustomField21       string `json:"new_custom_field_21"`
	NewCustomField22       string `json:"new_custom_field_22"`
	NewCustomField23       string `json:"new_custom_field_23"`
	NewCustomField24       string `json:"new_custom_field_24"`
	NewCustomField25       string `json:"new_custom_field_25"`
	NewCustomField26       string `json:"new_custom_field_26"`
	NewCustomField27       string `json:"new_custom_field_27"`
	NewCustomField28       string `json:"new_custom_field_28"`
	NewCustomField29       string `json:"new_custom_field_29"`
	NewCustomField30       string `json:"new_custom_field_30"`
	NewCustomField31       string `json:"new_custom_field_31"`
	NewCustomField32       string `json:"new_custom_field_32"`
	NewCustomField33       string `json:"new_custom_field_33"`
	NewCustomField34       string `json:"new_custom_field_34"`
	NewCustomField35       string `json:"new_custom_field_35"`
	NewCustomField36       string `json:"new_custom_field_36"`
	NewCustomField37       string `json:"new_custom_field_37"`
	NewCustomField38       string `json:"new_custom_field_38"`
	NewCustomField39       string `json:"new_custom_field_39"`
	NewCustomField40       string `json:"new_custom_field_40"`
	NewCustomField41       string `json:"new_custom_field_41"`
	NewCustomField42       string `json:"new_custom_field_42"`
	NewCustomField43       string `json:"new_custom_field_43"`
	NewCustomField44       string `json:"new_custom_field_44"`
	NewCustomField45       string `json:"new_custom_field_45"`
	NewCustomField46       string `json:"new_custom_field_46"`
	NewCustomField47       string `json:"new_custom_field_47"`
	NewCustomField48       string `json:"new_custom_field_48"`
	NewCustomField49       string `json:"new_custom_field_49"`
	NewCustomField50       string `json:"new_custom_field_50"`
	NewCustomField51       string `json:"new_custom_field_51"`
	NewCustomField52       string `json:"new_custom_field_52"`
	NewCustomField53       string `json:"new_custom_field_53"`
	NewCustomField54       string `json:"new_custom_field_54"`
	NewCustomField55       string `json:"new_custom_field_55"`
	NewCustomField56       string `json:"new_custom_field_56"`
	NewCustomField57       string `json:"new_custom_field_57"`
	NewCustomField58       string `json:"new_custom_field_58"`
	NewCustomField59       string `json:"new_custom_field_59"`
	NewCustomField60       string `json:"new_custom_field_60"`
	NewCustomField61       string `json:"new_custom_field_61"`
	NewCustomField62       string `json:"new_custom_field_62"`
	NewCustomField63       string `json:"new_custom_field_63"`
	NewCustomField64       string `json:"new_custom_field_64"`
	NewCustomField65       string `json:"new_custom_field_65"`
	NewCustomField66       string `json:"new_custom_field_66"`
	NewCustomField67       string `json:"new_custom_field_67"`
	NewCustomField68       string `json:"new_custom_field_68"`
	NewCustomField69       string `json:"new_custom_field_69"`
	NewCustomField70       string `json:"new_custom_field_70"`
	NewCustomField71       string `json:"new_custom_field_71"`
	NewCustomField72       string `json:"new_custom_field_72"`
	NewCustomField73       string `json:"new_custom_field_73"`
	NewCustomField74       string `json:"new_custom_field_74"`
	NewCustomField75       string `json:"new_custom_field_75"`
	NewCustomField76       string `json:"new_custom_field_76"`
	NewCustomField77       string `json:"new_custom_field_77"`
	NewCustomField78       string `json:"new_custom_field_78"`
	NewCustomField79       string `json:"new_custom_field_79"`
	NewCustomField80       string `json:"new_custom_field_80"`
	NewCustomField81       string `json:"new_custom_field_81"`
	NewCustomField82       string `json:"new_custom_field_82"`
	NewCustomField83       string `json:"new_custom_field_83"`
	NewCustomField84       string `json:"new_custom_field_84"`
	NewCustomField85       string `json:"new_custom_field_85"`
	NewCustomField86       string `json:"new_custom_field_86"`
	NewCustomField87       string `json:"new_custom_field_87"`
	NewCustomField88       string `json:"new_custom_field_88"`
	NewCustomField89       string `json:"new_custom_field_89"`
	NewCustomField90       string `json:"new_custom_field_90"`
	NewCustomField91       string `json:"new_custom_field_91"`
	NewCustomField92       string `json:"new_custom_field_92"`
	NewCustomField93       string `json:"new_custom_field_93"`
	NewCustomField94       string `json:"new_custom_field_94"`
	NewCustomField95       string `json:"new_custom_field_95"`
	NewCustomField96       string `json:"new_custom_field_96"`
	NewCustomField97       string `json:"new_custom_field_97"`
	NewCustomField98       string `json:"new_custom_field_98"`
	NewCustomField99       string `json:"new_custom_field_99"`
	NewCustomField100      string `json:"new_custom_field_100"`
	NewCustomField101      string `json:"new_custom_field_101"`
	NewCustomField102      string `json:"new_custom_field_102"`
	NewCustomField103      string `json:"new_custom_field_103"`
	NewCustomField104      string `json:"new_custom_field_104"`
	NewCustomField105      string `json:"new_custom_field_105"`
	NewCustomField106      string `json:"new_custom_field_106"`
	NewCustomField107      string `json:"new_custom_field_107"`
	NewCustomField108      string `json:"new_custom_field_108"`
	NewCustomField109      string `json:"new_custom_field_109"`
	NewCustomField110      string `json:"new_custom_field_110"`
	NewCustomField111      string `json:"new_custom_field_111"`
	NewCustomField112      string `json:"new_custom_field_112"`
	NewCustomField113      string `json:"new_custom_field_113"`
	NewCustomField114      string `json:"new_custom_field_114"`
	NewCustomField115      string `json:"new_custom_field_115"`
	NewCustomField116      string `json:"new_custom_field_116"`
	NewCustomField117      string `json:"new_custom_field_117"`
	NewCustomField118      string `json:"new_custom_field_118"`
	NewCustomField119      string `json:"new_custom_field_119"`
	NewCustomField120      string `json:"new_custom_field_120"`
	NewCustomField121      string `json:"new_custom_field_121"`
	NewCustomField122      string `json:"new_custom_field_122"`
	NewCustomField123      string `json:"new_custom_field_123"`
	NewCustomField124      string `json:"new_custom_field_124"`
	NewCustomField125      string `json:"new_custom_field_125"`
	NewCustomField126      string `json:"new_custom_field_126"`
	NewCustomField127      string `json:"new_custom_field_127"`
	NewCustomField128      string `json:"new_custom_field_128"`
	NewCustomField129      string `json:"new_custom_field_129"`
	NewCustomField130      string `json:"new_custom_field_130"`
	NewCustomField131      string `json:"new_custom_field_131"`
	NewCustomField132      string `json:"new_custom_field_132"`
	NewCustomField133      string `json:"new_custom_field_133"`
	NewCustomField134      string `json:"new_custom_field_134"`
	NewCustomField135      string `json:"new_custom_field_135"`
	NewCustomField136      string `json:"new_custom_field_136"`
	NewCustomField137      string `json:"new_custom_field_137"`
	NewCustomField138      string `json:"new_custom_field_138"`
	NewCustomField139      string `json:"new_custom_field_139"`
	NewCustomField140      string `json:"new_custom_field_140"`
	NewCustomField141      string `json:"new_custom_field_141"`
	NewCustomField142      string `json:"new_custom_field_142"`
	NewCustomField143      string `json:"new_custom_field_143"`
	NewCustomField144      string `json:"new_custom_field_144"`
	NewCustomField145      string `json:"new_custom_field_145"`
	NewCustomField146      string `json:"new_custom_field_146"`
	NewCustomField147      string `json:"new_custom_field_147"`
	NewCustomField148      string `json:"new_custom_field_148"`
	NewCustomField149      string `json:"new_custom_field_149"`
	NewCustomField150      string `json:"new_custom_field_150"`
	NewCustomField151      string `json:"new_custom_field_151"`
	NewCustomField152      string `json:"new_custom_field_152"`
	NewCustomField153      string `json:"new_custom_field_153"`
	NewCustomField154      string `json:"new_custom_field_154"`
	NewCustomField155      string `json:"new_custom_field_155"`
	NewCustomField156      string `json:"new_custom_field_156"`
	NewCustomField157      string `json:"new_custom_field_157"`
	NewCustomField158      string `json:"new_custom_field_158"`
	NewCustomField159      string `json:"new_custom_field_159"`
	NewCustomField160      string `json:"new_custom_field_160"`
	NewCustomField161      string `json:"new_custom_field_161"`
	NewCustomField162      string `json:"new_custom_field_162"`
	NewCustomField163      string `json:"new_custom_field_163"`
	NewCustomField164      string `json:"new_custom_field_164"`
	NewCustomField165      string `json:"new_custom_field_165"`
	NewCustomField166      string `json:"new_custom_field_166"`
	NewCustomField167      string `json:"new_custom_field_167"`
	NewCustomField168      string `json:"new_custom_field_168"`
	NewCustomField169      string `json:"new_custom_field_169"`
	NewCustomField170      string `json:"new_custom_field_170"`
	NewCustomField171      string `json:"new_custom_field_171"`
	NewCustomField172      string `json:"new_custom_field_172"`
	NewCustomField173      string `json:"new_custom_field_173"`
	NewCustomField174      string `json:"new_custom_field_174"`
	NewCustomField175      string `json:"new_custom_field_175"`
	NewCustomField176      string `json:"new_custom_field_176"`
	NewCustomField177      string `json:"new_custom_field_177"`
	NewCustomField178      string `json:"new_custom_field_178"`
	NewCustomField179      string `json:"new_custom_field_179"`
	NewCustomField180      string `json:"new_custom_field_180"`
	NewCustomField181      string `json:"new_custom_field_181"`
	NewCustomField182      string `json:"new_custom_field_182"`
	NewCustomField183      string `json:"new_custom_field_183"`
	NewCustomField184      string `json:"new_custom_field_184"`
	NewCustomField185      string `json:"new_custom_field_185"`
	NewCustomField186      string `json:"new_custom_field_186"`
	NewCustomField187      string `json:"new_custom_field_187"`
	NewCustomField188      string `json:"new_custom_field_188"`
	NewCustomField189      string `json:"new_custom_field_189"`
	NewCustomField190      string `json:"new_custom_field_190"`
	NewCustomField191      string `json:"new_custom_field_191"`
	NewCustomField192      string `json:"new_custom_field_192"`
	NewCustomField193      string `json:"new_custom_field_193"`
	NewCustomField194      string `json:"new_custom_field_194"`
	NewCustomField195      string `json:"new_custom_field_195"`
	NewCustomField196      string `json:"new_custom_field_196"`
	NewCustomField197      string `json:"new_custom_field_197"`
	NewCustomField198      string `json:"new_custom_field_198"`
	NewCustomField199      string `json:"new_custom_field_199"`
	NewCustomField200      string `json:"new_custom_field_200"`
	NewCustomPlanField1    string `json:"new_custom_plan_field_1"`
	NewCustomPlanField2    string `json:"new_custom_plan_field_2"`
	NewCustomPlanField3    string `json:"new_custom_plan_field_3"`
	NewCustomPlanField4    string `json:"new_custom_plan_field_4"`
	NewCustomPlanField5    string `json:"new_custom_plan_field_5"`
	NewCustomPlanField6    string `json:"new_custom_plan_field_6"`
	NewCustomPlanField7    string `json:"new_custom_plan_field_7"`
	NewCustomPlanField8    string `json:"new_custom_plan_field_8"`
	NewCustomPlanField9    string `json:"new_custom_plan_field_9"`
	NewCustomPlanField10   string `json:"new_custom_plan_field_10"`
}

type StoryDeleteEvent struct {
	Event          EventType `json:"event,omitempty"`
	EventFrom      string    `json:"event_from,omitempty"`
	Referer        string    `json:"referer,omitempty"`
	WorkspaceID    string    `json:"workspace_id,omitempty"`
	CurrentUser    string    `json:"current_user,omitempty"`
	ID             string    `json:"id,omitempty"`
	OpType         string    `json:"op_type,omitempty"`
	OldIterationID string    `json:"old_iteration_id,omitempty"`
	Secret         string    `json:"secret,omitempty"`
	RioToken       string    `json:"rio_token,omitempty"`
	DevProxyHost   string    `json:"devproxy_host,omitempty"`
	QueueID        string    `json:"queue_id,omitempty"`
	EventID        string    `json:"event_id,omitempty"`
	Created        string    `json:"created,omitempty"`
}
